[package]
name = "serde_urlencoded"
version = "0.7.1" # bump in documentation link and in README on update
authors = ["Anthony Ramine <n.oxyde@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nox/serde_urlencoded"
documentation = "https://docs.rs/serde_urlencoded/0.7.1/serde_urlencoded/"
description = "`x-www-form-urlencoded` meets Serde"
categories = ["encoding", "web-programming"]
keywords = ["serde", "serialization", "urlencoded"]
exclude = ["/.travis.yml", "/bors.toml"]
edition = "2018"

[features]
default = ["ryu"]

[dependencies]
# Percent encoding and mapping of query string to pair of key-values
form_urlencoded = "1.0.1"
# Used for internal buffering during deserialization
indexmap = "1.8.1"
# Fast integer serialization
itoa = "1.0.1"
# Fast and better-looking float serialization
ryu = { version = "1.0.9", optional = true }
# Contains the Serializer and Deserializer traits
serde = "1.0.136"

[dev-dependencies]
# For the assert_matches! macro
matches = "0.1.9"
# Some tests use structs that derive Serialize / Deserialize
serde = { version = "1.0.136", features = ["derive"] }
